version: "3.1"

services:
  db:
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "snippetbox"
    volumes:
      - db:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db:
